spring:
  application:
    name: sample

server:
  port: 19090

resilience4j:
  circuitbreaker:
    configs:
      default:  # ?? ?? ??
        registerHealthIndicator: true  # ??????? ?? ??? ?? ???? ??? ???? ???? ??
        # ?? ????? ??? ? ??? ???? ???? ??? ??
        # COUNT_BASED: ??? N?? ?? ??? ???? ??? ??
        # TIME_BASED: ??? N? ??? ?? ??? ???? ??? ??
        slidingWindowType: COUNT_BASED  # ???? ???? ??? ?? ? ??(COUNT_BASED)?? ??
        # ???? ???? ??? ??
        # COUNT_BASED? ??: ?? N?? ??? ??
        # TIME_BASED? ??: ?? N? ??? ??? ??
        slidingWindowSize: 5  # ???? ???? ??? 5?? ??? ??
        minimumNumberOfCalls: 5  # ?? ????? ???? ?? ??? ???? ?? ?? 5? ??
        slowCallRateThreshold: 100  # ?? ??? ??? ? ???(100%)? ???? ?? ????? ??
        slowCallDurationThreshold: 60000  # ?? ??? ?? ??(???)??, 60? ?? ??? ?? ??? ??
        failureRateThreshold: 50  # ???? ? ???(50%)? ???? ?? ????? ??
        permittedNumberOfCallsInHalfOpenState: 3  # ?? ????? Half-open ???? ???? ?? ?? ?? 3?? ??
        # ?? ????? Open ???? Half-open ??? ???? ?? ???? ??
        waitDurationInOpenState: 20s  # Open ???? Half-open ??? ???? ?? ???? ??? 20?? ??

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  prometheus:
    metrics:
      export:
        enabled: true